### ISSUE TITLE
RSS-Feed

### ISSUE THREAD

**Issue by budumlu** [okfde/edulabs#352]
Hallo,

würde mich sehr freuen, wenn ihr noch einen RSS-Feed für euren Blog bereitstellen könntet...

https://help.github.com/articles/atom-rss-feeds-for-github-pages/

Beste Grüße!

**Comment by mneuschaefer** [comment]
Hallo,
es gibt bereits einen feed unter  https://edulabs.de/feed.xml , dazu ergänzen wir noch ein Icon. 
viele Grüße,
Markus

**Comment by aivuk** [comment]
Icon added!
