### ISSUE TITLE
Karla font loaded from Google

### ISSUE THREAD

**Issue by niccokunzmann** [okfde/edulabs#557]
You load the font of Karla from Google.
There is no need to help Google track your users.

This commit should be applicaple to your repository, too, removing Google from the informed servers.
https://github.com/Brandenburger-Maker/Brandenburger-Maker.github.io/pull/8/commits/fdad4cd43745677e949fa666b9205688b7fc6767

**Comment by aivuk** [comment]
Thanks for pointing it up. I usually try to remove any content loading from Google to prevent their tracking (well, at least try to make it a bit harder) but left this out. Fixed on 4d2b6101df3d1aad82bcdc2f8cc560c2ce7654ea
