### ISSUE TITLE
Formular kann nicht abgesendet werden

### ISSUE THREAD

**Issue by niccokunzmann** [okfde/edulabs#564]
Wenn ich auf https://edulabs.de/oer/add gehe und das Formular ausfülle,
und ich auf SENDEN klicke,
dann sehe ich

> Beim Absenden deiner Karte ist etwas schiefgelaufen. Bitte versuche es in einer Minute erneut und halte dieses Fenster geöffnet.

Und wenn ich die Konsole öffe, dann sehe ich, dass diese Nachricht immer erscheint, wenn ich auf SENDEN klicke:

`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://staticman.okfn.de/v2/entry/okfde/edulabs/master/dw. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).`

Als Antwort bekomme ich 502 ohne Response Body.

```
502
POST
dw
staticman.okfn.de
xhr
```

<summary>Form Data
<details>
<pre>
fields[art] | oer
-- | --
fields[author-email] | kristine.kolbe@medialepfade.org
fields[author-name] | Mediale+Pfade
fields[author-website] | MedialePfade.org
fields[dauer] | dauer-3
fields[desc] | Für+Grundschulkinder+eignet+sich+der+Micro:bit+oder+[Calliope+mini].+Auf+farbigem+Karton+gestalten+die+Lernenden+aus+Kupferklebefolie+und+Steck-LEDs+eine+geschlossene+Form+(Stromkreis)+und+bringen+die+LED+zum+leuchten+und+Blinken.
fields[desc2] | empty
fields[fach] | {…}
0 | fach-4
1 | fach-5
fields[lernziele] | Mit+Hilfe+der+Microcontroller+Microbit+oder+Calliope+mini+kann+die+LED+z.B.+über+einfaches+Einschalten+der+Knöpfe+(A+B)+gesteuert+werden,+sie+kann+angeschaltet+werden+oder+blinken.+Auslöser+kann+etwa+auch+das+Schütteln+des+Boards+(Bewegungssensor)+sein.+Durch+den+verbauten+Temperatursensor+ist+es+sogar+möglich,+dass+eine+bestimmten+Temperatur+erreicht+sein+muss,+damit+die+LED+leuchtet.
fields[link] | https://pad.medialepfade.net/MAKINGSCHULE-elektro-basteln
fields[lizenz] | lizenz-3
fields[long-fach] | {…}
0 | long-fach-7
1 | long-fach-8
2 | long-fach-9
3 | long-fach-12
fields[medien] | {…}
0 | medien-2
1 | medien-4
fields[tags] | Calliope,MicroBit,LED
fields[tipp] | Die+Erfahrungen+mit+dem+Material+sind+im+Material+beschrieben+und+können+gerne+erweitert+werden.
fields[titel] | Leuchtende+Kunstwerke+auf+Papier+mit+externer+LED-Steuerung
fields[title] | 7f79s
fields[top-kmk] | {…}
0 | top-kmk-3
1 | top-kmk-5
fields[visible] | 0
fields[vorbereitungszeit] | vorbereitungszeit-1
fields[zielgruppe] | {…}
0 | zielgruppe-2
1 | zielgruppe-3
options[origin] | https://edulabs.de/oer/add
</pre>
</details></summary>

**Comment by maximusvo** [comment]
fixed
